# Generated by Django 5.2.3 on 2025-12-04 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('salt_key', models.CharField(max_length=255)),
                ('policy_config', models.JSONField(blank=True, default=dict)),
                ('retention_policy', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint_metadata', models.JSONField(blank=True, default=dict)),
                ('runtime_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.organization')),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_id', models.CharField(blank=True, max_length=255, null=True)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('start_ts', models.DateTimeField(auto_now_add=True)),
                ('end_ts', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='running', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.agent')),
            ],
            options={
                'db_table': 'runs',
                'ordering': ['-start_ts'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mock_state_pointer', models.CharField(max_length=1024)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment_snapshots', to='api.run')),
            ],
            options={
                'db_table': 'environment_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq_no', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(choices=[('agent', 'Agent'), ('tool', 'Tool'), ('system', 'System'), ('user', 'User')], max_length=20)),
                ('type', models.CharField(choices=[('reasoning', 'Reasoning'), ('action_request', 'Action Request'), ('action_response', 'Action Response'), ('final_output', 'Final Output'), ('error', 'Error')], max_length=30)),
                ('payload', models.TextField()),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_events', to='api.run')),
            ],
            options={
                'db_table': 'trace_events',
                'ordering': ['run', 'seq_no'],
            },
        ),
        migrations.CreateModel(
            name='TraceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aggregation_pointer', models.CharField(max_length=512)),
                ('summary_metrics', models.JSONField(blank=True, default=dict)),
                ('object_store_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trace_record', to='api.run')),
            ],
            options={
                'db_table': 'trace_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(choices=[('agent', 'Agent'), ('tool', 'Tool'), ('system', 'System'), ('user', 'User'), ('admin', 'Admin')], max_length=20)),
                ('type', models.CharField(choices=[('reasoning', 'Reasoning'), ('action_request', 'Action Request'), ('action_response', 'Action Response'), ('final_output', 'Final Output'), ('error', 'Error'), ('config_change', 'Config Change'), ('admin_action', 'Admin Action'), ('policy_update', 'Policy Update')], max_length=30)),
                ('payload', models.TextField()),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.organization')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='audit_logs_organiz_9c8c67_idx'), models.Index(fields=['actor'], name='audit_logs_actor_eb54d4_idx'), models.Index(fields=['type'], name='audit_logs_type_05a55c_idx'), models.Index(fields=['user_id'], name='audit_logs_user_id_73c422_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['agent', 'status'], name='runs_agent_i_4a9add_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['start_ts'], name='runs_start_t_6e5062_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentsnapshot',
            index=models.Index(fields=['snapshot_id'], name='environment_snapsho_81b80b_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentsnapshot',
            index=models.Index(fields=['run'], name='environment_run_id_8ae8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='traceevent',
            index=models.Index(fields=['run', 'seq_no'], name='trace_event_run_id_8850bb_idx'),
        ),
        migrations.AddIndex(
            model_name='traceevent',
            index=models.Index(fields=['timestamp'], name='trace_event_timesta_d218b8_idx'),
        ),
        migrations.AddIndex(
            model_name='traceevent',
            index=models.Index(fields=['actor'], name='trace_event_actor_62081e_idx'),
        ),
        migrations.AddIndex(
            model_name='traceevent',
            index=models.Index(fields=['type'], name='trace_event_type_84c792_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traceevent',
            unique_together={('run', 'seq_no')},
        ),
    ]
