# Generated by Django 5.2.3 on 2025-12-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.CharField(choices=[('agent', 'Agent'), ('tool', 'Tool'), ('system', 'System'), ('user', 'User'), ('admin', 'Admin'), ('redteam', 'Red Team')], max_length=20),
        ),
        migrations.AlterField(
            model_name='traceevent',
            name='actor',
            field=models.CharField(choices=[('agent', 'Agent'), ('tool', 'Tool'), ('system', 'System'), ('user', 'User'), ('redteam', 'Red Team')], max_length=20),
        ),
    ]
