# Generated by Django 5.2.3 on 2025-12-04 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_auditlog_actor_alter_traceevent_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='salt_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AgentAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=8)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'is_active'], name='agent_api_k_agent_i_39fb5c_idx'), models.Index(fields=['key_hash'], name='agent_api_k_key_has_def180_idx'), models.Index(fields=['key_prefix'], name='agent_api_k_key_pre_fc4581_idx'), models.Index(fields=['expires_at'], name='agent_api_k_expires_2715aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MTLSCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('certificate', models.TextField()),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=64)),
                ('issuer', models.CharField(max_length=512)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtls_certificates', to='api.organization')),
            ],
            options={
                'db_table': 'mtls_certificates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='mtls_certif_organiz_e4f9f9_idx'), models.Index(fields=['fingerprint'], name='mtls_certif_fingerp_8154c6_idx'), models.Index(fields=['valid_until'], name='mtls_certif_valid_u_eca6c6_idx'), models.Index(fields=['common_name'], name='mtls_certif_common__3d64a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token'), ('ci', 'CI/CD Token')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'token_type', 'is_active'], name='oauth_token_user_id_b06da1_idx'), models.Index(fields=['token_hash'], name='oauth_token_token_h_80c709_idx'), models.Index(fields=['expires_at'], name='oauth_token_expires_bf1131_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSaltKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_salt', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salt_keys', to='api.organization')),
            ],
            options={
                'db_table': 'organization_salt_keys',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_f8869b_idx'), models.Index(fields=['expires_at'], name='organizatio_expires_29e59a_idx')],
                'unique_together': {('organization', 'version')},
            },
        ),
    ]
